name: gestor_inventario_ropa
description: Aplicaci贸n de gesti贸n de inventario de ropa con autenticaci贸n y sincronizaci贸n offline/online.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.3
  image_picker: ^1.1.0
  firebase_storage: ^11.7.0
  pdf: ^3.10.4
  open_file: ^3.3.2 
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  assets:
    - assets/images/bg.jpg