// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNPHyjj2L0njzm6bBGLW_lSP-4cpfR98g',
    appId: '1:335321512309:web:536b99c19c3c905c18bb3c',
    messagingSenderId: '335321512309',
    projectId: 'proyectomovil-adcb4',
    authDomain: 'proyectomovil-adcb4.firebaseapp.com',
    storageBucket: 'proyectomovil-adcb4.firebasestorage.app',
    measurementId: 'G-R7PHV8LJYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDmmJY5twtnUV1lkujMJ7TaK3AlD3OxyA',
    appId: '1:335321512309:android:b459d2b97f7c5b3f18bb3c',
    messagingSenderId: '335321512309',
    projectId: 'proyectomovil-adcb4',
    storageBucket: 'proyectomovil-adcb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQ7s8lgNwIVa-_qY9y9Vgb-plpDIc0d4',
    appId: '1:335321512309:ios:5534433e53f26cc718bb3c',
    messagingSenderId: '335321512309',
    projectId: 'proyectomovil-adcb4',
    storageBucket: 'proyectomovil-adcb4.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrQ7s8lgNwIVa-_qY9y9Vgb-plpDIc0d4',
    appId: '1:335321512309:ios:5534433e53f26cc718bb3c',
    messagingSenderId: '335321512309',
    projectId: 'proyectomovil-adcb4',
    storageBucket: 'proyectomovil-adcb4.firebasestorage.app',
    iosBundleId: 'com.example.proyectofinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNPHyjj2L0njzm6bBGLW_lSP-4cpfR98g',
    appId: '1:335321512309:web:0968a8e337a2937e18bb3c',
    messagingSenderId: '335321512309',
    projectId: 'proyectomovil-adcb4',
    authDomain: 'proyectomovil-adcb4.firebaseapp.com',
    storageBucket: 'proyectomovil-adcb4.firebasestorage.app',
    measurementId: 'G-K3WMY5CB9E',
  );
}
