name: Flutter Web → GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter (3.32.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - - name: Analyze
  run: |
    # Opción A: usar el analizador de Dart con flags
    dart analyze --no-fatal-warnings --no-fatal-infos \
      || true
    # Opción B (equivalente con Flutter):
    # flutter analyze || true

      # Para repos de proyecto (NO username.github.io):
      # usa el nombre real del repo entre barras: /proyectoMovil/
      - name: Build Web (release)
        run: flutter build web --release --base-href "/proyectoMovil/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4